WSO2 Open Banking API Manager Puppet Scripts
wso2/puppet-open-banking pull request #4
Opened 2019-08-20 09:42 UTC by KalanaDananjaya

## Purpose
> This PR includes the basic puppet scripts for deploying WSO2 OB API Manager with h2 database

## Goals
> Deploying WSO2 OBAM v1.4 using puppet scripts

## Approach
> An individual module is created for OBAM deployment.It should be run separately using profile=obam140.When running the product, OBKM should be started before starting OBAM

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Test environment
> JDK - Oracle jdk1.8.0_161
   OS - Ubuntu 18.04
   Database - H2

2019-08-20 10:19 UTC, VimukthiPerera requested changes

2019-08-20 10:24 UTC, Savidude requested changes

2019-08-21 04:35 UTC, Savidude approved these changes

2019-08-21 04:43 UTC, VimukthiPerera approved these changes

2019-08-21 04:44 UTC, merged

2022-07-04 03:13 UTC, KalanaDananjaya commented on modules/obam140/templates/carbon-home/repository/conf/datasources/master-datasources.xml.erb
> +                    <defaultAutoCommit>false</defaultAutoCommit>
Fixed

2022-07-04 03:13 UTC, KalanaDananjaya commented on modules/obam140/templates/carbon-home/repository/conf/datasources/master-datasources.xml.erb
> +		            <url><%= @db_apimgt_stat_url %></url>
Fixed

2022-07-04 03:13 UTC, KalanaDananjaya commented on modules/obam140/manifests/params.pp
> +
Fixed

2022-07-04 03:13 UTC, KalanaDananjaya commented on modules/obam140/manifests/init.pp
> +
Fixed

2022-07-04 03:13 UTC, KalanaDananjaya commented on modules/obam140/templates/carbon-home/repository/deployment/server/executionplans/global_FreqPerDay.siddhiql.erb
> +#  Copyright (c) 2019 WSO2, Inc. http://www.wso2.org
Fixed